modLoader = "javafml"
loaderVersion = "[43,)"
license="Apache2.0"
[[mods]]
modId = "biomeapireforged"
version = "${version}"
displayName = "Biome API Reforged"
displayURL="https://github.com/YeoXuHang/BiomeApiReforged"
credits="Fabric team for creating fabric and this api, all other contributers who contributed to the original over the years."
authors="YeoXuHang"
logoFile="icon.png"
description = '''
Porting Fabric Biome Api to Forge version
'''
[[dependencies.biomeapireforged]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.biomeapireforged]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
